# Generated by Django 4.2.1 on 2023-07-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ManyToManyField(related_name='project_admins', to=settings.AUTH_USER_MODEL)),
                ('bugs', models.ManyToManyField(related_name='project_bugs', to='debugger.bug')),
                ('developers', models.ManyToManyField(related_name='project_developers', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ManyToManyField(related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('submitters', models.ManyToManyField(related_name='project_submitters', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='project_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(related_name='user_notifications', to='debugger.message')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('admin', models.ManyToManyField(related_name='institution_admin', to=settings.AUTH_USER_MODEL)),
                ('developers', models.ManyToManyField(related_name='institution_developers', to=settings.AUTH_USER_MODEL)),
                ('pending', models.ManyToManyField(related_name='institution_pending_users', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ManyToManyField(related_name='institution_project_manager', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='institution_projects', to='debugger.project')),
                ('submitters', models.ManyToManyField(related_name='institution_bug_submitter', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='institution_users', related_query_name='institution_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.TextField(blank=True, null=True)),
                ('new', models.TextField()),
                ('property', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_history', to='debugger.bug')),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_changer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='comments',
            field=models.ManyToManyField(related_name='ticket_comments', to='debugger.message'),
        ),
        migrations.AddField(
            model_name='bug',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_fixer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bug',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
